# Site settings
title: Backend Developer
name : 신명훈
email: tity0009@naver.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "향수 추천 웹사이트(Franding)에서 장바구니에 상품 담기 기능 및 향수 추천과 검색 기능을 담당하였습니다. 검색 기능의 속도를 개선시기키 위해서 redis 서버를 이용하였으며, 향수 추천 기능에서 rag를 이용하여 상품 추천 시 정확도를 높이기 위해 노력했습니다."
meta_author: MyeongHoon Sin

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #18bc9c #80B3FF
  primary-rgb: "24,288,156" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: MyeongHoonSin
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/SinMoonGh
    type: brands
  - title: blog
    url: https://velog.io/@fishing_bear99/posts
    type: solid

# Postal address (add as many lines as necessary)
address:
  - line: 진주시 가좌동 진주대로
  #- line: Beverly Hills, CA 90210

# Credits content
credits: '해당 웹 사이트는 <a href="http://startbootstrap.com">Bootstrap</a>을 이용해서 포토폴리오용으로 제작되었습니다.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
